services:
  git-server:
    image: jkarlos/git-server-docker
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
      - ~/.ssh:/git-server/keys
      - ../../tmp/repos:/git-server/repos